#!/bin/bash
# (C) 2020 Deutsche Telekom AG.
#
# Deutsche Telekom AG and all other contributors /
# copyright owners license this file to you under the Apache
# License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Fail script if any command fails.
set -euo pipefail

# Get script path.
if test "$(uname -s)" = 'Darwin'; then
    script_path="$(stat -f '%N' "${0}" | xargs dirname)"
else
    script_path="$(readlink -f "${0}" | xargs dirname)"
fi

rm -rf /tmp/cxxpool
git clone https://github.com/bloomen/cxxpool.git /tmp/cxxpool
cp -rf /tmp/cxxpool/src/cxxpool.h "${script_path}/../src/lib/util/cxxpool.h"
rm -rf /tmp/cxxpool

rm -rf /tmp/magic_enum
git clone https://github.com/Neargye/magic_enum.git /tmp/magic_enum
cp /tmp/magic_enum/include/magic_enum.hpp "${script_path}/../src/lib/util/magic_enum.hpp"
rm -rf /tmp/magic_enum
